### ISSUE TITLE
Core dumped during the compiler process with ICC 22

### ISSUE THREAD

**Issue by ywlds** [gtfock-chem/GTFock#11]
Hi, 
I am trying to use the ICC 22(I am not available to find ICC 17) to compile the gtfock-simint, and then run into the core dump.
Is this bug similar to what you meet in ICC 18(you mentioned). 

![image](https://user-images.githubusercontent.com/14145559/178981442-62aa2876-4e07-42a0-959c-224c5d11935a.png)

**Comment by huanghua1994** [comment]
Hi,

I have not tried the new Intel compiler (the oneAPI toolkit) yet. ICC 2020 update 4 (icc (ICC) 19.1.3.304 20200925) works on my machine. You may also consider using a smaller number of threads in make (e.g. make -j4 instead of make -j16) and see if the problem still exists.

**Comment by ywlds** [comment]
Hi, I try this not works. 
But I change the setting to 
from 
CC=icc CXX=icpc cmake ../ -DSIMINT_VECTOR=micavx512 -DSIMINT_C_FLAGS="-O3;-g" -DCMAKE_INSTALL_PREFIX=./install

to 
CC=icc CXX=icpc cmake ../ -DSIMINT_VECTOR=micavx512 -DSIMINT_C_FLAGS="-O2;-g" -DCMAKE_INSTALL_PREFIX=./install
 
Now seems it passed the compile.
But I do not know how much it influences the speed.

Many thanks,

**Comment by huanghua1994** [comment]
Glad to know that. The performance difference between O3 and O2 is usually very small, personally speaking I will not worry about that.

**Comment by ywlds** [comment]
> Hi,
> 
> I have not tried the new Intel compiler (the oneAPI toolkit) yet. ICC 2020 update 4 (icc (ICC) 19.1.3.304 20200925) works on my machine. You may also consider using a smaller number of threads in make (e.g. make -j4 instead of make -j16) and see if the problem still exists.

To config libcint as you describe, I did not find the libcint.a.
Do we need to configure it by ourself?

2. libcint
cd $WORK_TOP
git clone https://github.com/gtfock-chem/libcint.git
cd libcint
# Adjust the Makefile according to the directory you compiled Simint and your system
make libcint.a

**Comment by huanghua1994** [comment]
You need to modify the Makefile in libcint directory (to give the correct SIMINT path and use the correct compiler), then run `make libcint.a`.

**Comment by ywlds** [comment]
> You need to modify the Makefile in libcint directory (to give the correct SIMINT path and use the correct compiler), then run `make libcint.a`.

Many thanks,
I see two things may need to modify.

ERD_LIB    = /global/homes/h/huangh/scratch/OptErd_Makefile/lib
SIMINT_DIR = /global/homes/h/huangh/scratch/gtfock-simint/build-avx512/install

Here seems two directory.
One is the SIMINT_DIR this I can change accordingly.
How about the ERD_LIB. Is there something extra I should install?

**Comment by huanghua1994** [comment]
You can ignore the ERD_LIB, it's a deprecated library. Also, make sure that you use `make libcint.a` instead of `make` or `make all`.

**Comment by ywlds** [comment]
> You can ignore the ERD_LIB, it's a deprecated library. Also, make sure that you use `make libcint.a` instead of `make` or `make all`.

I change the directory as this.
ERD_LIB    = /opt/tiger/GTFock/gtfock-simint/templib
#SIMINT_DIR = /global/homes/h/huangh/scratch/gtfock-simint/build-avx512/install
SIMINT_DIR = /opt/tiger/GTFock/gtfock-simint/build-avx512/install

INC=-I. -I${SIMINT_DIR}/include

and some compile setting as 
#OPTFLAGS = -m64 -qno-offload
to 
OPTFLAGS = -m64 

and 
CFLAGS = -O3 -Wall -w2 -qopenmp -g
to 
CFLAGS = -O3 -Wall -w -fopenmp -g
CFLAGS += -Wunknown-pragmas -Wunused-variable

then I run
make libcint.a
I get error as 

![image](https://user-images.githubusercontent.com/14145559/178991673-c921568c-6e37-421e-bc73-b0c58dbdb466.png)

**Comment by huanghua1994** [comment]
You should also change the `CC` `CXX` `FC` values in the Makefile. Now you are using the system's default `cc` command (most likely a old version of GCC), so it haserrors.

**Comment by ywlds** [comment]
> You should also change the `CC` `CXX` `FC` values in the Makefile. Now you are using the system's default `cc` command (most likely a old version of GCC), so it haserrors.

You are right.
Now I change this two part accordingly.

CXX=icpc
CC=icc -std=gnu99

Seems ok now.
![image](https://user-images.githubusercontent.com/14145559/178992832-36dbd097-bc0c-4ea8-945f-77fb4e0c5638.png)
